// Code generated by "stringer -type=Foo -output=foo_str.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[foo1-0]
	_ = x[foo2-1]
	_ = x[foo3-2]
	_ = x[bar1-3]
	_ = x[bar2-4]
}

const _Foo_name = "foo1foo2foo3bar1bar2"

var _Foo_index = [...]uint8{0, 4, 8, 12, 16, 20}

func (i Foo) String() string {
	if i < 0 || i >= Foo(len(_Foo_index)-1) {
		return "Foo(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Foo_name[_Foo_index[i]:_Foo_index[i+1]]
}
